### ISSUE TITLE
Do not use a modal dialog when data could not be fetched

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-con#30]
The modal dialog that is shown when the data _check for update_ could not be performed is rather scary :). Often conference attendees do not have reliable internet connection, so this message appears more than expected. Instead, we should show a subtle message that says _updates performed x hours ago_.

**Comment by cpetrov** [comment]
Now a [snackbar-like](https://material.google.com/components/snackbars-toasts.html) widget will be shown instead of a modal dialog. Also to make it clear whether shown data is current, a message is included in the _Tracks_ and _My Schedule_ pages showing last update. 

Thanks for the feedback!

| My Schedule | Tracks |
| --- | --- |
| ![1](https://cloud.githubusercontent.com/assets/2341769/18789352/01dfa5a0-81ab-11e6-9b07-a8f2ab0224ee.png) | ![2](https://cloud.githubusercontent.com/assets/2341769/18789353/01e31af0-81ab-11e6-8696-af4ec54ab445.png) |
